windows_container:
  image: cirrusci/windowsservercore:2016
  
download_innosetup_task:      
  download_script: 
    - powershell -Command "(New-Object Net.WebClient).DownloadFile('http://jrsoftware.org/download.php/is.exe', 'is.exe')"
    - .\is.exe

check_java_task:      
  download_script: 
    - java --version
